### ISSUE TITLE
Question: Simultaneous Import and export? 

### ISSUE THREAD

**Issue by jauyzed** [dlueth/qoopido.docker.mariadb#1]
Hello,

I am working on a solution to perform a dump and restore on mariadb's. For example: dump from prod and restore to dev.  The hosts are actual DB's and chances are that prod dump file might be several gigs. I have to use volume container to store the dumps. Once the dump is complete, the restore process should begin. This could be a monthly process for now. If all works well, the I might implement on other env's. Would I be able to implement this with your docker project/containers? Thanks!

**Comment by dlueth** [comment]
Afaik the current containers "create dump on shutdown" does not work (any more) due to changed internals of docker :( Because of that I did change my containers to store the DB natively on mounted volumes from the host and switched the base to Alpine during the process (https://hub.docker.com/r/qoopido/alpine-mariadb/).

I did get what you want (which is quite similar to what my usecase was) but I guess this is currently impossible to achieve :(

**Comment by jauyzed** [comment]
Well, it doesn't have to be separate containers. The dump could start when I do `docker compose up` . The same container could do both export and import. something like `mysqldump -h1 -u1 -p1 | mysql -h 2 - u 2 - p2`. I will be passing the host details for both from docker compose file. The only caveat is  the dump files are huge and need to be stored on host volume through volume container and be consumed by restore process from the same place.

**Comment by dlueth** [comment]
If a customizable shell script being run on docker-compose up would be enough this should be fairly easy to implement ;)

Is it enough for what you have in mind?

**Comment by jauyzed** [comment]
I did create a new image from official mariadb and volumed in a host directory- ran a shell shell script inside maria db container to dump and restore from prod to dev. Issue is resolved. 

Thanks!
